knpu_oauth2_client:
    clients:
        google:
           types
            type: facebook
            client_id: '%env(resolve:FACEBOOK_ID)%'
            client_secret: '%env(resolve:FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.12
            